bin-path: /bin/gandalf-ssh
log:
  use-stderr: true
database:
  url: $MONGODB_ADDR:$MONGODB_PORT
  name: gandalf
git:
  bare:
    location: /var/lib/gandalf/repositories
    template: /home/git/bare-template
host: $GANDALF_HOST
bind: "0.0.0.0:8000"
uid: git
