bin-path: /usr/bin/gandalf-ssh
database:
  url: $MONGODB_PORT_27017_TCP_ADDR:27017
  name: gandalf
git:
  bare:
    location: /var/lib/gandalf/repositories
    template: /home/git/bare-template
host: localhost
bind: "0.0.0.0:8000"
uid: git
api:
  request:
    maxMemory: 2097152
repository:
  tempDir: /tmp
log:
  disable-syslog: true
